# Generated by Django 4.2.7 on 2023-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default={'language': 'en', 'profile_header': '', 'subscribe_to_newsletter': False}),
        ),
    ]
